### ISSUE TITLE
Chrome reports GSP violation

### ISSUE THREAD

**Issue by defmans7** [code-debug228/HostetskiGPT#25]
Issue:
Clicking Generate Answer, opens a new window and an error is logged to the console: 

`Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-Fl6mtwZocgt1Y7dCXgcTbDUbE'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.`

Tested in latest Chrome Version 120.0.6099.5 (also incognito) and Edge. 

Expected behaviour: 
Click Generate Answer creates a new ChatGPT response based on saved prompt.

May attempt a fix and pull request when I have some time.

**Comment by MrCyjaneK** [comment]
I can confirm, same issue happens on my end.

**Comment by MrCyjaneK** [comment]
Disabling `app.csp_enabled` fixed this issue on my end

**Comment by code-debug228** [comment]
Yes, there is such a problem. It arose due to some updates in FreeScout, but the module has not yet been updated to work correctly with new versions. I will try to release a new version of the module with a fix for this problem within a few days, unfortunately, due to my studies I don’t have time to work on the module.

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/3443
