### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by ruess** [code-debug228/HostetskiGPT#6]
Hi there,

I've set everything up as correctly as I can see. I've even upgraded my Open API account so that there was no problem with my API keys being outside of the trial. I've refreshed my API token and placed it into /Modules/HostetskiGPT/Http/Controllers/HostetskiGPTController.php. 

Nonetheless, my Freescout App log file shows this error when I try to generate a ChatGPT response in a thread:
Unsuccessful response. HTTP status code: 401 (Unauthorized). {"userId":1,"email":"[my_email_address]","exception":"[object] (Tectalic\\OpenAi\\ClientException(code: 0): Unsuccessful response. HTTP status code: 401 (Unauthorized). at /public_html/Modules/HostetskiGPT/vendor/tectalic/openai/src/Handlers/ChatCompletions.php:150) 

Any thoughts?

**Comment by AliakseyM** [comment]
We have not encountered this specific issue before, aside from cases where an incorrect API key was used. Therefore, it is essential to double-check your API key and ensure that it is correct and has the necessary permissions to access the OpenAI API.

If the issue persists, please send an email to support@cloudcenter.ovh so that we can provide you with a test OpenAI key. This will help eliminate the possibility of the problem being related to your existing API key or account.
